
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.POSTGRES_PRISMA_URL ?? process.env.DATABASE_URL;
const directUrl = process.env.POSTGRES_URL_NON_POOLING ?? process.env.DIRECT_URL ?? databaseUrl;

if (!databaseUrl) throw new Error("DATABASE_URL or POSTGRES_PRISMA_URL is required");
if (!directUrl) throw new Error("DIRECT_URL or POSTGRES_URL_NON_POOLING is required");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
    directUrl,
  },
});
